# Generated by Django 5.0.1 on 2024-05-21 21:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM_app', '0003_alter_addresses_phone_alter_addresses_pincode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_items',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order_items',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_dim',
            field=models.CharField(choices=[('12x15', '12X15'), ('12x8', '12X8'), ('12x18', '12X18'), ('16x24', '16X24'), ('20x30', '20X30')], max_length=20),
        ),
    ]
