# Generated by Django 5.0.1 on 2024-05-22 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EM_app', '0004_order_order_address_order_payment_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_dim',
            field=models.CharField(choices=[('12x15', '12X15'), ('12x8', '12X8'), ('12x18', '12X18'), ('20x30', '20X30'), ('16x24', '16X24')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
